services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbit:
    image: rabbitmq:4.1.1-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  worker:
    build: .
    restart: unless-stopped
    env_file: .env
    command:
      [
        "celery",
        "-A",
        "app.infrastructure.celery.celery_app",
        "worker",
        "--loglevel=info",
      ]
    depends_on:
      rabbit:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  beat:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      CELERYBEAT_SCHEDULE_FILE: /celerybeat/celerybeat-schedule
    volumes:
      - beat_data:/celerybeat
    command:
      [
        "celery",
        "-A",
        "app.infrastructure.celery.celery_app",
        "beat",
        "--schedule=/celerybeat/celerybeat-schedule",
        "--loglevel=info",
      ]
    depends_on:
      rabbit:
        condition: service_healthy

volumes:
  pgdata:
  rabbit_data:
  beat_data:

networks:
  default:
    name: task-service
